name: gen_article
description: A simple command-line application to generate articles from templates.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  intl: ^0.17.0
  args: ^2.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
